### ISSUE TITLE
Blis license violation in wheels and sdist

### ISSUE THREAD

**Issue by isuruf** [explosion/cython-blis#10]
The wheels and sdist don't have the BSD license copyright, nor the disclaimer, but they are mandatory.

**Comment by honnibal** [comment]
Sorry about this! Will get new wheels out asap.

**Comment by honnibal** [comment]
Actually the library should really be re-licensed BSD as well. It's pretty weird to have a license that's not compatible with Blis's.

**Comment by isuruf** [comment]
> Actually the library should really be re-licensed BSD as well. It's pretty weird to have a license that's not compatible with Blis's.

That's your choice. You can keep have any license you want as long as the BSD license text of blis is distributed along with the sdist and wheels

**Comment by honnibal** [comment]
Okay, done now. Thanks again for pointing this out. I regret that there was a bit of a delay, getting the pip versions rebuilt takes a bit of care.

**Comment by isuruf** [comment]
Only the sdist was fixed. wheels still don't have the license and copyright text.
