### ISSUE TITLE
setup.py should respect CC

### ISSUE THREAD

**Issue by benjaminp** [explosion/cython-blis#11]
If you set `CC=/some/custom/toolchain/path/bin/gcc` when running `setup.py build_ext`, `setup.py` will still invoke the `gcc` on `$PATH` if there is one. This is contrary to the normal distutils behavior, which is that `setup.py` will respect the environment settings.

The problem seems to be `get_compiler_name`:
https://github.com/explosion/cython-blis/blob/84c54c9fb5f8b3fc08df73adbdf15b263e62bf08/setup.py#L140-L152
This function turns most compiler paths into base names that have to be resolved by looking through `$PATH`.

**Comment by honnibal** [comment]
Fixed in the next release.

**Comment by benjaminp** [comment]
Thank you for following up.
