### ISSUE TITLE
Can't install blis via pip due to gcc mavx2 flag confusion in bli_amaxv_zen_int.c

### ISSUE THREAD

**Issue by spinkyspider** [explosion/cython-blis#12]
Trying to install spacy python package on FreeBSD v12. Fails on dependency install of the blis package which throws "no such instruction" errors regarding AVX2 assembly commands when trying to compile the bli_amaxv_zen_int.c file with '-mavx2' and '-march=core-avx2' compiler flags set. In the attached file, I have included the output from gcc as to what it gets from the CPU, which is accurate, to the best of my knowledge. It's a sandybridge and definitely has AVX2 capabilities.

Is there a way to unset those avx2 flags? Or what is the right solution to this?

The relevant articles I've found refer to this or that software package not being up to date that then affects compilation. All those packages, I've checked on my system and they are all current.

thoughts anyone?

cheers,
~spider

[compile_output.txt](https://github.com/explosion/cython-blis/files/3511447/compile_output.txt)

**Comment by honnibal** [comment]
Thanks for the detailed report. The easiest interim solution will be to use conda. If you do need to use pip (and personally, I do prefer pip), this might be an occasion to try out this new package, and let me know how you go: https://github.com/regro/conda-press

I'd like to get the package fixed for you, but you're shaving the wrong yak by trying to disable the avx2 instructions. That will make the library deathly slow -- you definitely need the vectorisation.

I think the thing to look into is your gcc version. The idea was that everyone would be able to use the wheel installation, but I guess FreeBSD uses a different libc, so the wheel isn't compatible?
