### ISSUE TITLE
Update to the latest flame/blis?

### ISSUE THREAD

**Issue by rhazegh** [explosion/cython-blis#29]
I am having performance issues with this library on my AMD Ryzen 3900X CPU and was looking in the code to see if I can find out why this is happening. See this issue for reference: https://github.com/conda-forge/cython-blis-feedstock/issues/18

I have installed this through conda forge:

```
# conda list | grep blis
cython-blis               0.4.1            py38h1e0a361_1    conda-forge
```

It looks like `cython-blis` is using a version of `flame/blis` from Mar 12, 2019 (https://github.com/honnibal/blis/tree/2c59c46b57cb3517d33b350cc5d18022e1fe93f4) 

It appears that since then, some new optimizations are added for AMD in the `flame/blis` library and they have added support for `zen2` (https://github.com/flame/blis/tree/master/config/zen2)

Is it possible to update `cython-blis` to take advantage of these new optimizations?

**Comment by honnibal** [comment]
Currently working on this, thanks for your patience.

**Comment by rhazegh** [comment]
@honnibal Thank you. Please let me know if there is anything I can help with.

**Comment by honnibal** [comment]
v0.7.0 now up. Working on the conda package.

**Comment by rhazegh** [comment]
@honnibal Thank you very much for making this happen. Is there any chance we could also get a 0.7 conda package as well? If there is anything you think I can help with please let me know.
