### ISSUE TITLE
Wheels for blis for Python-3.11

### ISSUE THREAD

**Issue by adrianeboyd** [explosion/cython-blis#86]
any idea when blis for Python-3.11 will be released to the public ?

_Originally posted by @stonebig in https://github.com/explosion/cython-blis/issues/85#issuecomment-1328222694_

**Comment by adrianeboyd** [comment]
There are python 3.11 wheels for blis v0.7.9, which is the current version used by thinc/spacy. Are you using blis outside of spacy?

We are aware of some bugs that lead to segfaults in some of the haswell kernels for BLIS 0.9.0, so our general recommendation is to use v0.7.x for now, but if you know for sure that you're using an unrelated architecture, blis v0.9.x might be okay to use. Do you need wheels for v0.9.x for use outside of spacy?

**Comment by stonebig** [comment]
OK, I didn't think to look at older versions. It's for spacy indeed

**Comment by adrianeboyd** [comment]
Installing spacy through the quickstart instructions should work on pip and conda for python 3.11 and get the right version of blis: https://spacy.io/usage

If you just want to install blis from a binary wheel, you can use `pip install --prefer-binary blis`.

**Comment by stonebig** [comment]
YeS YeS, you can close my issue
